version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: new_shoes_store
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  
  redis:
    container_name: redis-cache-nst
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes: 
     - redis:/data
volumes:
  redis:
   
  