version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: new_shoes_store
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    
   
  